language: c

# S3 key and secret in travis conf
addons:
  artifacts:
    s3_region: "eu-central-1"
    paths:
      - wheelhouse

notifications:
  email: false

sudo: required

services:
  - docker

env:
  matrix:
  - SOURCE_TAG=lxml-3.6.0 IMAGE=lxml-manylinux1_x86_64
  - SOURCE_TAG=master IMAGE=lxml-manylinux1_x86_64
#  - SOURCE_TAG=lxml-3.2.3 IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
#  - SOURCE_TAG=master IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32

install:
  - make lxml-manylinux1_x86_64

script:
  - make checkout-source
  - docker run -t --rm -v $(pwd):/io $IMAGE $PRE_CMD make -C /io wheels
  - ls wheelhouse/
