notifications:
  email: false

sudo: required

services:
  - docker

env:
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PRE_CMD=""
  - DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32

matrix:
  include:
    - env: TAG=lxml-3.2.3

install:
  - docker pull $DOCKER_IMAGE
  - git clone git@github.com:lxml/lxml.git
  - git checkout $TAG

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
