notifications:
  email: false

sudo: required

services:
  - docker

env:
  matrix:
  - TAG=lxml-3.2.3 DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - TAG=lxml-3.2.3 DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
        
install:
  - docker pull $DOCKER_IMAGE
  - git clone https://github.com/lxml/lxml.git
  - cd git checkout $TAG

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
